on: [push, pull_request]
name: Test
jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0
      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run ./...
  test-with-module:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest]
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
      GOPROXY: "https://proxy.golang.org"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build .
      - name: Test
        run: go test -race -mod=vendor .

  test-with-gopath:
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: ls
        run: ls -la
      - name: get module
        run: go get
      - name: Test
        run: go test -race ./...
  coverage:
    needs: [test-with-module]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          go-version: 1.13.x
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: c91f892b8957ff9b030830b15d17d9b8e51dc0657f82ad3143ef9c4f79c757f0
        with:
          coverageCommand: go test -v -race -coverprofile cover.out ./...
          debug: true
